import { chromium } from "playwright-core";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on("pageerror", (e) => console.log("PAGEERROR:", String((e && e.message) || e).slice(0, 200)));
await page.goto("http://localhost:7334/#/market/BTS_USD?tf=discrete", { waitUntil: "domcontentloaded", timeout: 30000 });
await page.waitForTimeout(8000);
const out = await page.evaluate(() => {
  const log = [];
  const cvs = Array.from(document.querySelectorAll("canvas.mkt-canvas"));
  const c = cvs.find((x) => { try { return !!x._discreteRec && x._discreteRec.xs.length; } catch (e) { return false; } });
  if (!c) return { nodiscrete: true };
  const rec = c._discreteRec;
  log.push("recKeys:" + Object.keys(rec).join(","));
  log.push("nxs:" + rec.xs.length + " view:" + JSON.stringify(rec.view));
  const r = c.getBoundingClientRect();
  const i = Math.floor(rec.xs.length / 2);
  const sx = r.left + rec.xs[i], sy = r.top + rec.ys[i];
  log.push("aim:" + Math.round(sx) + "," + Math.round(sy) + " rect:" + Math.round(r.left) + "," + Math.round(r.top) + "," + Math.round(r.width) + "x" + Math.round(r.height));
  c.dispatchEvent(new MouseEvent("mousemove", { bubbles: true, clientX: sx, clientY: sy }));
  const tip = document.querySelector("[data-discrete-tip]");
  log.push("tip:" + (tip ? tip.style.display + "|" + tip.textContent.slice(0, 50) : "NONE"));
  return { log };
});
console.log(JSON.stringify(out, null, 1));
await browser.close();
