/* globals.d.ts — cross-file browser globals for tsc --checkJs (DEV-ONLY,
 * never loaded by index.html, never shipped as code). Every name below is a
 * top-level `var` in exactly one vanilla/js/** file, shared because classic
 * <script> tags share one scope. Start as `any`; the JSDoc seams pass
 * refines these to real types per module (see tooling/check_types.sh).
 * Removal: delete this file + the gate if TypeScript ever becomes
 * unobtainable (the app runs without it).
 */
declare var AboutUI: any;
declare var Account: any;
declare var AccountNet: any;
declare var AccountNetDepth: any;
declare var AccountNetES: any;
declare var AccountNetworkCopy: any;
declare var AccountNetworkUI: any;
declare var AccountUI: any;
declare var AccountsUI: any;
declare var ApiLab: any;
declare var ApiLabUI: any;
declare var App: any;
declare var Asset: any;
declare var AssetFeedUI: any;
declare var AssetManageUI: any;
declare var AssetOps: any;
declare var AssetUI: any;
declare var AuthUI: any;
declare var BarterUI: any;
declare var BitsharesURI: any;
declare var BorrowUI: any;
declare var Chain: any;
declare var ChartsLwc: any;
declare var CreateAccountUI: any;
declare var CreateWorkerUI: any;
declare var Credit: any;
declare var CreditDetailUI: any;
declare var CreditSamet: any;
declare var CreditUI: any;
declare var Crypto: any;
declare var DashboardUI: any;
declare var DebitUI: any;
declare var DiscreteCharts: any;
declare var EsLab: any;
declare var EsLabResults: any;
declare var EsLabRun: any;
declare var EsLabUI: any;
declare var Explorer: any;
declare var ExplorerAssets: any;
declare var ExplorerBlocks: any;
declare var ExplorerRender: any;
declare var ExplorerTabs: any;
declare var ExplorerUI: any;
declare var FavouritesUI: any;
declare var FeedHistory: any;
declare var FeesUI: any;
declare var Format: any;
declare var Forms: any;
declare var Gateway: any;
declare var GatewayUI: any;
declare var Geo: any;
declare var GovAnalytics: any;
declare var HelpUI: any;
declare var HistoryCap: any;
declare var HistoryExport: any;
declare var HistoryNotice: any;
declare var HistorySummary: any;
declare var Htlc: any;
declare var HtlcUI: any;
declare var I: any;
declare var Icon: any;
declare var Indicators: any;
declare var InstantTradeUI: any;
declare var Market: any;
declare var MarketBook: any;
declare var MarketCandles: any;
declare var MarketCharts: any;
declare var MarketDesk: any;
declare var MarketFills: any;
declare var MarketInd: any;
declare var MarketHops: any;
declare var MarketNet: any;
declare var MarketNetUI: any;
declare var MarketOrders: any;
declare var MarketPicker: any;
declare var MarketUI: any;
declare var PairContext: any;
declare var MenuUI: any;
declare var MiscUI: any;
declare var NetChrome: any;
declare var NetGestures: any;
declare var NetPaint: any;
declare var NewsUI: any;
declare var Notify: any;
declare var NotifyHost: any;
declare var NotifyRules: any;
declare var NotifyUI: any;
declare var Offline: any;
declare var OpsUI: any;
declare var PasswordUI: any;
declare var Pool: any;
declare var PoolAssets: any;
declare var PoolDetailUI: any;
declare var PoolGraph: any;
declare var PoolHistory: any;
declare var PoolNet: any;
declare var PoolNetPhys: any;
declare var PoolNetUI: any;
declare var PoolUI: any;
declare var Prediction: any;
declare var PredictionUI: any;
declare var Proposal: any;
declare var ProposalMisc: any;
declare var ProposalTicket: any;
declare var ProposalUI: any;
declare var ReferralsUI: any;
declare var Router: any;
declare var SametUI: any;
declare var SettingsNodes: any;
declare var SettingsPage: any;
declare var SettingsPrefs: any;
declare var SignMode: any;
declare var Store: any;
declare var TicketUI: any;
declare var TopOpsUI: any;
declare var TourUI: any;
declare var TradeCancel: any;
declare var TradeForm: any;
declare var TradeUI: any;
declare var TransferConfirm: any;
declare var TransferUI: any;
declare var Trollbox: any;
declare var TrollboxUI: any;
declare var Tx: any;
declare var TxBuilder: any;
declare var TxBuilderUI: any;
declare var VestingUI: any;
declare var Vote: any;
declare var VoteSlate: any;
declare var VoteUI: any;
declare var ViewingAs: any;
declare var Wallet: any;
declare var WalletUI: any;
declare var touchable: <T extends HTMLElement>(el: T) => T;
declare var DOM: {
  el: {
    (doc: Document, tag: "a", text?: string | null, cls?: string | null): HTMLAnchorElement;
    (doc: Document, tag: "button", text?: string | null, cls?: string | null): HTMLButtonElement;
    (doc: Document, tag: "input", text?: string | null, cls?: string | null): HTMLInputElement;
    (doc: Document, tag: "select", text?: string | null, cls?: string | null): HTMLSelectElement;
    (doc: Document, tag: "textarea", text?: string | null, cls?: string | null): HTMLTextAreaElement;
    (doc: Document, tag: string, text?: string | null, cls?: string | null): HTMLElement;
  };
  clear: (root: HTMLElement) => void;
  text: (el: HTMLElement, text: string | null | undefined) => HTMLElement;
  attrs: (el: HTMLElement, obj: Record<string, string | null | undefined>) => HTMLElement;
  status: (wrap: HTMLElement, text: string | null | undefined) => HTMLElement;
  error: (wrap: HTMLElement, text: string | null | undefined) => HTMLElement;
  skel: (wrap: HTMLElement, rows?: number) => HTMLElement;
  append: (wrap: HTMLElement, ...nodes: HTMLElement[]) => HTMLElement;
  pageHead: (doc: Document, titleText: string, iconName?: string | null | undefined) => HTMLElement;
};
interface Window {
  touchable: <T extends HTMLElement>(el: T) => T;
  DOM: {
    el: {
    (doc: Document, tag: "a", text?: string | null, cls?: string | null): HTMLAnchorElement;
    (doc: Document, tag: "button", text?: string | null, cls?: string | null): HTMLButtonElement;
    (doc: Document, tag: "input", text?: string | null, cls?: string | null): HTMLInputElement;
    (doc: Document, tag: "select", text?: string | null, cls?: string | null): HTMLSelectElement;
    (doc: Document, tag: "textarea", text?: string | null, cls?: string | null): HTMLTextAreaElement;
    (doc: Document, tag: string, text?: string | null, cls?: string | null): HTMLElement;
  };
    clear: (root: HTMLElement) => void;
    text: (el: HTMLElement, text: string | null | undefined) => HTMLElement;
    attrs: (el: HTMLElement, obj: Record<string, string | null | undefined>) => HTMLElement;
    status: (wrap: HTMLElement, text: string | null | undefined) => HTMLElement;
    error: (wrap: HTMLElement, text: string | null | undefined) => HTMLElement;
    skel: (wrap: HTMLElement, rows?: number) => HTMLElement;
    append: (wrap: HTMLElement, ...nodes: HTMLElement[]) => HTMLElement;
    pageHead: (doc: Document, titleText: string, iconName?: string | null | undefined) => HTMLElement;
  };
}
declare var BRAINKEY_DICT: any;
declare var ConfirmDialog: any;
declare var Duration: any;
declare var PredictionHelpers: any;
declare var PredictionFlows: any;
declare var TradePanels: any;
declare var TransferPreview: any;
declare var TransferPropose: any;
declare var Overlay: any;
declare var UnlockConfirm: any;
declare var TableRenderer: any;
declare var EventDelegate: any;
declare var nobleGetPublicKey: any;
declare var nobleSignAsync: any;
declare var nobleGetSharedSecret: any;
declare var I18n: any;
declare var chrome: any;
declare var browser: any;
declare var Buffer: any;
declare var NodeDiscover: any;
