/* ApiLab: curated WebSocket API catalog for the #/api-lab node prober.
 * Owns: the method catalog (group/login/method/params/tier per entry),
 *   param coercion (curated strings -> typed RPC params), and run() — the
 *   single call path the desk uses. No DOM, no signing, no key material.
 * Consumes: Chain.call (sole socket owner — generic login(entry.login) then
 *   the method, so database/history/network_node/network_broadcast/asset/
 *   orders/block/custom all flow through the shared socket; no second
 *   connection ever).
 * Globals/side effects: exposes global ApiLab only.
 * Created by: api-lab design 2026-10-03 (Option B), AFK build.
 * Extended: 2026-10-03 comprehensive coverage (Tier 1+2+3: full accounts,
 *   market history, positions, pools/HTLC/credit/tickets, witnesses/workers,
 *   history/block/asset/orders/custom reads).
 *
 * CHAIN TRUTH (#4 wins; verified 2026-10-03 against the sparse checkout):
 * - database_api.hpp: get_objects:92, get_block_header:162,
 *   get_block_header_batch:173, get_block:182, get_transaction:190,
 *   get_recent_transaction_by_id:200, get_chain_properties:209,
 *   get_global_properties:214, get_config:219, get_chain_id:224,
 *   get_dynamic_global_properties:229, get_next_object_id:240,
 *   get_key_references:254, get_account_id_from_string:275, get_accounts:287,
 *   get_full_accounts:309, get_top_voters:319, get_account_by_name:326,
 *   get_account_references:333, lookup_account_names:342, lookup_accounts:357,
 *   get_account_balances:371, get_named_account_balances:375,
 *   get_balance_objects:382, get_vested_balances:390, get_vesting_balances:397,
 *   get_account_count:402, get_asset_id_from_string:413, get_assets:425,
 *   list_assets:435, lookup_asset_symbols:444, get_asset_count:450,
 *   get_assets_by_issuer:460, get_limit_orders:475,
 *   get_limit_orders_by_account:495, get_account_limit_orders:524,
 *   get_call_orders:538, get_call_orders_by_account:548, get_settle_orders:558,
 *   get_settle_orders_by_account:569, get_collateral_bids:581,
 *   get_margin_positions:591, get_ticker:618, get_24_volume:626,
 *   get_order_book:636, get_top_markets:646, get_trade_history:662,
 *   get_trade_history_by_sequence:677, list_liquidity_pools:701,
 *   get_liquidity_pools_by_asset_a:723, get_liquidity_pools_by_asset_b:746,
 *   get_liquidity_pools_by_one_asset:769, get_liquidity_pools_by_both_assets:794,
 *   get_liquidity_pools:815, get_liquidity_pools_by_share_asset:834,
 *   get_liquidity_pools_by_owner:856, list_samet_funds:881,
 *   get_samet_funds_by_owner:901, get_samet_funds_by_asset:922,
 *   list_credit_offers:947, get_credit_offers_by_owner:967,
 *   get_credit_offers_by_asset:988, list_credit_deals:1007,
 *   get_credit_deals_by_offer_id:1027, get_credit_deals_by_offer_owner:1048,
 *   get_credit_deals_by_borrower:1069, get_credit_deals_by_debt_asset:1090,
 *   get_credit_deals_by_collateral_asset:1111, get_witnesses:1129,
 *   get_witness_by_account:1136, lookup_witness_accounts:1145,
 *   get_witness_count:1151, get_committee_members:1164,
 *   get_committee_member_by_account:1172, lookup_committee_member_accounts:1181,
 *   get_committee_count:1188, get_all_workers:1201, get_workers_by_account:1208,
 *   get_worker_count:1213, lookup_vote_ids:1233, get_transaction_hex:1244,
 *   get_transaction_hex_without_sig:1251, get_required_signatures:1262,
 *   get_potential_signatures:1273, get_potential_address_signatures:1281,
 *   get_required_fees:1313, get_proposed_transactions:1326,
 *   get_blinded_balances:1337, get_withdraw_permissions_by_giver:1352,
 *   get_withdraw_permissions_by_recipient:1365, get_htlc:1381,
 *   get_htlc_by_from:1391, get_htlc_by_to:1403, list_htlcs:1414,
 *   list_tickets:1435, get_tickets_by_account:1455.
 * - api.hpp: history_api get_account_history:89,
 *   get_account_history_by_time:112, get_account_history_by_operations:128,
 *   get_account_history_operations:146, get_relative_account_history:167,
 *   get_block_operation_history:186, get_block_operations_by_time:202,
 *   get_fill_order_history:212, get_market_history:229,
 *   get_market_history_buckets:239, get_liquidity_pool_history:266,
 *   get_liquidity_pool_history_by_sequence:295 (login "history");
 *   block_api get_blocks:320 (login "block");
 *   network_broadcast_api broadcast_transaction:352 (login
 *   "network_broadcast"); network_node_api get_info:401,
 *   get_connected_peers:412, get_potential_peers:430 (login "network_node");
 *   asset_api get_asset_holders:573, get_asset_holders_count:581,
 *   get_all_asset_holders:587 (login "asset"); orders_api
 *   get_tracked_groups:623, get_grouped_limit_orders:636 (login "orders");
 *   custom_operations_api get_storage_info:683 (login "custom_operations").
 * - No debug_api class exists in api.hpp (classes: history/block/
 *   network_broadcast/network_node/crypto/asset/orders/custom_operations) —
 *   so the debug tier probes login "debug" and surfaces the node's real
 *   rejection instead of inventing methods. #1 Console.jsx:7-22 eval box is
 *   the anti-pattern: never eval, never expose wallet/debug handles.
 * MONEY DISCIPLINE (#6): params/results stay raw here; the VIEW adds human
 *   hints via Format — this file formats nothing.
 */
var ApiLab = (function () {
  "use strict";

  /* Param types: string (free text), uint (non-negative integer string),
   * int (signed integer string, for sequence ids), bool, json (any JSON
   * value, parsed verbatim), strlist (JSON array of strings — one input box
   * holding e.g. ["1.2.0"]). One box per param keeps the desk
   * dependency-free; strlist/json accept pasted arrays. Optional blanks
   * coerce to null (the node's "omitted" sentinel for optional<> params). */
  var GROUPS = ["Database", "History", "Network", "Block", "Asset", "Orders", "Custom", "Debug"];

  /* Tier labels for the desk gate. read/fee run free; broadcast needs unlock
   * + per-call confirm (Transfer precedent); debug runs free but is expected
   * to fail on public nodes — the failure is the honest result. */
  var TIERS = { read: "read", fee: "fee", broadcast: "broadcast", debug: "debug" };

  /* P: one param descriptor. Params: name, type, o (optional extras:
   * required, example, hint, max). Returns the descriptor. Fails: never. */
  function P(name, type, o) {
    var e = o || {};
    return { name: name, type: type, required: e.required !== false,
      example: e.example || "", hint: e.hint || "", max: e.max || null };
  }

  /* METHODS: the curated catalog. login is the exact login-API name sent on
   * the shared socket (Chain.call(1, login, [])). Broadcast entries never
   * auto-run from a deep link (the desk enforces prefill+lock). */
  var METHODS = [
    { group: "Database", login: "database", method: "get_chain_id",
      tier: TIERS.read, src: "database_api.hpp:224",
      desc: "Chain ID of the connected node (matches wallet config).",
      params: [] },
    { group: "Database", login: "database", method: "get_dynamic_global_properties",
      tier: TIERS.read, src: "database_api.hpp:229",
      desc: "Head block, time, participation — the chain pulse.",
      params: [] },
    { group: "Database", login: "database", method: "get_config",
      tier: TIERS.read, src: "database_api.hpp:219",
      desc: "Chain constants (fees scale, percent bases).",
      params: [] },
    { group: "Database", login: "database", method: "get_chain_properties",
      tier: TIERS.read, src: "database_api.hpp:209",
      desc: "Current chain properties (fees, limits set by witnesses).",
      params: [] },
    { group: "Database", login: "database", method: "get_global_properties",
      tier: TIERS.read, src: "database_api.hpp:214",
      desc: "Global properties (committee-controlled parameters).",
      params: [] },
    { group: "Database", login: "database", method: "get_block",
      tier: TIERS.read, src: "database_api.hpp:182",
      desc: "One signed block by height.",
      params: [P("block_num", "uint", { example: "100916767",
        hint: "Positive block height." })] },
    { group: "Database", login: "database", method: "get_block_header",
      tier: TIERS.read, src: "database_api.hpp:162",
      desc: "Block header only (lighter than a full block).",
      params: [P("block_num", "uint", { example: "100916767" }),
        P("with_witness_signature", "bool", { required: false, example: "",
          hint: "Blank = omitted." })] },
    { group: "Database", login: "database", method: "get_block_header_batch",
      tier: TIERS.read, src: "database_api.hpp:173",
      desc: "Headers for a batch of heights (JSON array).",
      params: [P("block_nums", "json", { example: "[100916767,100916768]",
        hint: "JSON array of heights." }),
        P("with_witness_signatures", "bool", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_transaction",
      tier: TIERS.read, src: "database_api.hpp:190",
      desc: "One processed transaction by block + index in block.",
      params: [P("block_num", "uint", { example: "100916767" }),
        P("trx_in_block", "uint", { example: "0" })] },
    { group: "Database", login: "database", method: "get_recent_transaction_by_id",
      tier: TIERS.read, src: "database_api.hpp:200",
      desc: "Recent transaction by ID (40-hex ripemd160, NOT 64).",
      params: [P("txid", "string", { example: "9b3ed9b6d2656687ec49f8ff4ce023f9c5436e58",
        hint: "40 hex chars." })] },
    { group: "Database", login: "database", method: "get_next_object_id",
      tier: TIERS.read, src: "database_api.hpp:240",
      desc: "Next object id for a space/type pair (what the next create gets).",
      params: [P("space_id", "uint", { example: "1" }),
        P("type_id", "uint", { example: "2" }),
        P("with_pending_transactions", "bool", { example: "false" })] },
    { group: "Database", login: "database", method: "get_objects",
      tier: TIERS.read, src: "database_api.hpp:92",
      desc: "Any objects by 1.x.y / 2.x.y IDs.",
      params: [P("ids", "strlist", { example: '["1.2.0","1.3.0"]',
        hint: "JSON array of object IDs." })] },
    { group: "Database", login: "database", method: "get_account_by_name",
      tier: TIERS.read, src: "database_api.hpp:326",
      desc: "Account lookup — the canonical name search (not get_account).",
      params: [P("name", "string", { example: "committee-account" })] },
    { group: "Database", login: "database", method: "get_account_id_from_string",
      tier: TIERS.read, src: "database_api.hpp:275",
      desc: "Resolve a name-or-ID string to a 1.2.x id.",
      params: [P("name_or_id", "string", { example: "committee-account" })] },
    { group: "Database", login: "database", method: "get_accounts",
      tier: TIERS.read, src: "database_api.hpp:287",
      desc: "Batch account fetch by name-or-ID list.",
      params: [P("names_or_ids", "strlist", { example: '["committee-account","1.2.5"]' })] },
    { group: "Database", login: "database", method: "get_full_accounts",
      tier: TIERS.read, src: "database_api.hpp:309",
      desc: "Full account bundle (account + balances + orders + proposals).",
      params: [P("names_or_ids", "strlist", { example: '["committee-account"]' }),
        P("subscribe", "bool", { required: false, example: "",
          hint: "Blank = omitted." })] },
    { group: "Database", login: "database", method: "get_top_voters",
      tier: TIERS.read, src: "database_api.hpp:319",
      desc: "Top accounts by voting power (descending).",
      params: [P("limit", "uint", { example: "10", max: 1000 })] },
    { group: "Database", login: "database", method: "get_account_references",
      tier: TIERS.read, src: "database_api.hpp:333",
      desc: "Accounts that reference this account (auths, proxies).",
      params: [P("account", "string", { example: "committee-account" })] },
    { group: "Database", login: "database", method: "get_key_references",
      tier: TIERS.read, src: "database_api.hpp:254",
      desc: "Accounts linked to public keys (JSON array of keys).",
      params: [P("keys", "strlist", { example: '["BTS6..."]',
        hint: "JSON array of public keys." })] },
    { group: "Database", login: "database", method: "lookup_account_names",
      tier: TIERS.read, src: "database_api.hpp:342",
      desc: "Exact-name batch lookup (semantics identical to get_objects).",
      params: [P("names", "strlist", { example: '["committee-account"]' })] },
    { group: "Database", login: "database", method: "lookup_accounts",
      tier: TIERS.read, src: "database_api.hpp:357",
      desc: "Prefix search for account names.",
      params: [P("lower_bound_name", "string", { example: "committee" }),
        P("limit", "uint", { example: "10", max: 1000 })] },
    { group: "Database", login: "database", method: "get_account_balances",
      tier: TIERS.read, src: "database_api.hpp:371",
      desc: "Raw balances for an account (raw integers — see hint line).",
      params: [P("account", "string", { example: "committee-account" }),
        P("assets", "strlist", { example: '["1.3.0"]' })] },
    { group: "Database", login: "database", method: "get_named_account_balances",
      tier: TIERS.read, src: "database_api.hpp:375",
      desc: "Balances by account name + asset-id set (equivalent to above).",
      params: [P("name", "string", { example: "committee-account" }),
        P("assets", "strlist", { example: '["1.3.0"]' })] },
    { group: "Database", login: "database", method: "get_balance_objects",
      tier: TIERS.read, src: "database_api.hpp:382",
      desc: "Unclaimed balance objects for addresses (JSON array).",
      params: [P("addrs", "strlist", { example: '["BTS..."]' })] },
    { group: "Database", login: "database", method: "get_vested_balances",
      tier: TIERS.read, src: "database_api.hpp:390",
      desc: "Claimable amounts for vesting-balance ids (1.13.x array).",
      params: [P("objs", "strlist", { example: '["1.13.0"]' })] },
    { group: "Database", login: "database", method: "get_vesting_balances",
      tier: TIERS.read, src: "database_api.hpp:397",
      desc: "All vesting-balance objects owned by an account.",
      params: [P("account", "string", { example: "committee-account" })] },
    { group: "Database", login: "database", method: "get_account_count",
      tier: TIERS.read, src: "database_api.hpp:402",
      desc: "Total registered accounts (plain int, never money).",
      params: [] },
    { group: "Database", login: "database", method: "get_assets",
      tier: TIERS.read, src: "database_api.hpp:425",
      desc: "Batch asset fetch by symbol-or-ID list.",
      params: [P("symbols_or_ids", "strlist", { example: '["BTS","1.3.0"]' })] },
    { group: "Database", login: "database", method: "get_asset_id_from_string",
      tier: TIERS.read, src: "database_api.hpp:413",
      desc: "Resolve a symbol-or-ID string to a 1.3.x id.",
      params: [P("symbol_or_id", "string", { example: "BTS" })] },
    { group: "Database", login: "database", method: "list_assets",
      tier: TIERS.read, src: "database_api.hpp:435",
      desc: "Assets from a lower-bound symbol (prefix scan).",
      params: [P("lower_bound_symbol", "string", { example: "BTS" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "lookup_asset_symbols",
      tier: TIERS.read, src: "database_api.hpp:444",
      desc: "Exact-symbol batch lookup.",
      params: [P("symbols_or_ids", "strlist", { example: '["BTS"]' })] },
    { group: "Database", login: "database", method: "get_asset_count",
      tier: TIERS.read, src: "database_api.hpp:450",
      desc: "Total assets (plain int).",
      params: [] },
    { group: "Database", login: "database", method: "get_assets_by_issuer",
      tier: TIERS.read, src: "database_api.hpp:460",
      desc: "Assets issued by an account (paged by start id).",
      params: [P("issuer", "string", { example: "committee-account" }),
        P("start", "string", { example: "1.3.0" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "get_limit_orders",
      tier: TIERS.read, src: "database_api.hpp:475",
      desc: "Order book slice for asset pair A/B.",
      params: [P("a", "string", { example: "1.3.0" }),
        P("b", "string", { example: "1.3.121" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "get_limit_orders_by_account",
      tier: TIERS.read, src: "database_api.hpp:495",
      desc: "Limit orders of one account (limit/start optional, null = first page).",
      params: [P("account", "string", { example: "committee-account" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "",
          hint: "Order id 1.7.x, blank = first page." })] },
    { group: "Database", login: "database", method: "get_account_limit_orders",
      tier: TIERS.read, src: "database_api.hpp:524",
      desc: "Account orders in one market (price-paged).",
      params: [P("account", "string", { example: "committee-account" }),
        P("base", "string", { example: "1.3.0" }),
        P("quote", "string", { example: "1.3.121" }),
        P("limit", "uint", { example: "10", max: 100 }),
        P("ostart_id", "string", { required: false, example: "" }),
        P("ostart_price", "json", { required: false, example: "",
          hint: "Price object or blank." })] },
    { group: "Database", login: "database", method: "get_call_orders",
      tier: TIERS.read, src: "database_api.hpp:538",
      desc: "Margin call orders for a debt asset (earliest-call first).",
      params: [P("a", "string", { example: "1.3.113" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "get_call_orders_by_account",
      tier: TIERS.read, src: "database_api.hpp:548",
      desc: "Margin positions of one account (paged by start asset id).",
      params: [P("account", "string", { example: "committee-account" }),
        P("start", "string", { example: "1.3.0" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "get_settle_orders",
      tier: TIERS.read, src: "database_api.hpp:558",
      desc: "Force-settlement orders for an asset (earliest first).",
      params: [P("a", "string", { example: "1.3.113" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "get_settle_orders_by_account",
      tier: TIERS.read, src: "database_api.hpp:569",
      desc: "Settlement orders of one account (paged by start id).",
      params: [P("account", "string", { example: "committee-account" }),
        P("start", "string", { example: "1.4.0" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "get_collateral_bids",
      tier: TIERS.read, src: "database_api.hpp:581",
      desc: "Collateral bids for an asset (skip-start paging).",
      params: [P("a", "string", { example: "1.3.113" }),
        P("limit", "uint", { example: "10", max: 100 }),
        P("start", "uint", { example: "0" })] },
    { group: "Database", login: "database", method: "get_margin_positions",
      tier: TIERS.read, src: "database_api.hpp:591",
      desc: "Open margin positions of one account (first page).",
      params: [P("account", "string", { example: "committee-account" })] },
    { group: "Database", login: "database", method: "get_order_book",
      tier: TIERS.read, src: "database_api.hpp:636",
      desc: "Aggregated bids/asks for base/quote symbols.",
      params: [P("base", "string", { example: "BTS" }),
        P("quote", "string", { example: "USD" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "get_ticker",
      tier: TIERS.read, src: "database_api.hpp:618",
      desc: "24h ticker for base/quote symbols.",
      params: [P("base", "string", { example: "BTS" }),
        P("quote", "string", { example: "USD" })] },
    { group: "Database", login: "database", method: "get_24_volume",
      tier: TIERS.read, src: "database_api.hpp:626",
      desc: "24h volume for base/quote symbols.",
      params: [P("base", "string", { example: "BTS" }),
        P("quote", "string", { example: "USD" })] },
    { group: "Database", login: "database", method: "get_top_markets",
      tier: TIERS.read, src: "database_api.hpp:646",
      desc: "Top markets by volume (bounded limit).",
      params: [P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "get_trade_history",
      tier: TIERS.read, src: "database_api.hpp:662",
      desc: "Fills in a market between two UTC times (least-recent first).",
      params: [P("base", "string", { example: "BTS" }),
        P("quote", "string", { example: "USD" }),
        P("start", "string", { example: "2026-01-01T00:00:00",
          hint: "UTC, no timezone offset." }),
        P("stop", "string", { example: "2026-10-01T00:00:00" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "get_trade_history_by_sequence",
      tier: TIERS.read, src: "database_api.hpp:677",
      desc: "Fills by sequence pointer (for same-second overflow).",
      params: [P("base", "string", { example: "BTS" }),
        P("quote", "string", { example: "USD" }),
        P("start", "int", { example: "0", hint: "Sequence, 0 = most recent." }),
        P("stop", "string", { example: "2026-01-01T00:00:00" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "list_liquidity_pools",
      tier: TIERS.read, src: "database_api.hpp:701",
      desc: "Pools, paged (all optional, blank = first page).",
      params: [P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" }),
        P("with_statistics", "bool", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_liquidity_pools",
      tier: TIERS.read, src: "database_api.hpp:815",
      desc: "Pools by ID list (JSON array of 1.19.x).",
      params: [P("ids", "strlist", { example: '["1.19.0"]' }),
        P("subscribe", "bool", { required: false, example: "" }),
        P("with_statistics", "bool", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_liquidity_pools_by_asset_a",
      tier: TIERS.read, src: "database_api.hpp:723",
      desc: "Pools where asset A matches.",
      params: [P("asset", "string", { example: "1.3.0" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" }),
        P("with_statistics", "bool", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_liquidity_pools_by_asset_b",
      tier: TIERS.read, src: "database_api.hpp:746",
      desc: "Pools where asset B matches.",
      params: [P("asset", "string", { example: "1.3.0" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" }),
        P("with_statistics", "bool", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_liquidity_pools_by_one_asset",
      tier: TIERS.read, src: "database_api.hpp:769",
      desc: "Pools holding one asset on either side.",
      params: [P("asset", "string", { example: "1.3.0" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" }),
        P("with_statistics", "bool", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_liquidity_pools_by_both_assets",
      tier: TIERS.read, src: "database_api.hpp:794",
      desc: "Pools holding both assets.",
      params: [P("asset_a", "string", { example: "1.3.0" }),
        P("asset_b", "string", { example: "1.3.121" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" }),
        P("with_statistics", "bool", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_liquidity_pools_by_share_asset",
      tier: TIERS.read, src: "database_api.hpp:834",
      desc: "Pools by share-asset symbol-or-ID list.",
      params: [P("assets", "strlist", { example: '["1.3.0"]' }),
        P("subscribe", "bool", { required: false, example: "" }),
        P("with_statistics", "bool", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_liquidity_pools_by_owner",
      tier: TIERS.read, src: "database_api.hpp:856",
      desc: "Pools an account has a stake in.",
      params: [P("account", "string", { example: "committee-account" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" }),
        P("with_statistics", "bool", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "list_samet_funds",
      tier: TIERS.read, src: "database_api.hpp:881",
      desc: "Same-T funds, paged (blank = first page).",
      params: [P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_samet_funds_by_owner",
      tier: TIERS.read, src: "database_api.hpp:901",
      desc: "Same-T funds owned by an account.",
      params: [P("account", "string", { example: "committee-account" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_samet_funds_by_asset",
      tier: TIERS.read, src: "database_api.hpp:922",
      desc: "Same-T funds holding an asset.",
      params: [P("asset", "string", { example: "1.3.0" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "list_credit_offers",
      tier: TIERS.read, src: "database_api.hpp:947",
      desc: "Credit offers, paged (blank = first page).",
      params: [P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_credit_offers_by_owner",
      tier: TIERS.read, src: "database_api.hpp:967",
      desc: "Credit offers owned by an account.",
      params: [P("account", "string", { example: "committee-account" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_credit_offers_by_asset",
      tier: TIERS.read, src: "database_api.hpp:988",
      desc: "Credit offers in an asset.",
      params: [P("asset", "string", { example: "1.3.0" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "list_credit_deals",
      tier: TIERS.read, src: "database_api.hpp:1007",
      desc: "Credit deals, paged (blank = first page).",
      params: [P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_credit_deals_by_offer_id",
      tier: TIERS.read, src: "database_api.hpp:1027",
      desc: "Deals under one offer id (1.21.x).",
      params: [P("offer_id", "string", { example: "1.21.0" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_credit_deals_by_offer_owner",
      tier: TIERS.read, src: "database_api.hpp:1048",
      desc: "Deals under offers owned by an account.",
      params: [P("account", "string", { example: "committee-account" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_credit_deals_by_borrower",
      tier: TIERS.read, src: "database_api.hpp:1069",
      desc: "Deals borrowed by an account.",
      params: [P("account", "string", { example: "committee-account" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_credit_deals_by_debt_asset",
      tier: TIERS.read, src: "database_api.hpp:1090",
      desc: "Deals borrowing an asset.",
      params: [P("asset", "string", { example: "1.3.0" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_credit_deals_by_collateral_asset",
      tier: TIERS.read, src: "database_api.hpp:1111",
      desc: "Deals collateralized in an asset.",
      params: [P("asset", "string", { example: "1.3.0" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_witnesses",
      tier: TIERS.read, src: "database_api.hpp:1129",
      desc: "Witness objects by ID list.",
      params: [P("ids", "strlist", { example: '["1.6.1"]' })] },
    { group: "Database", login: "database", method: "get_witness_by_account",
      tier: TIERS.read, src: "database_api.hpp:1136",
      desc: "Witness record run by an account (or null).",
      params: [P("account", "string", { example: "committee-account" })] },
    { group: "Database", login: "database", method: "lookup_witness_accounts",
      tier: TIERS.read, src: "database_api.hpp:1145",
      desc: "Witness names from a lower bound (prefix scan).",
      params: [P("lower_bound_name", "string", { example: "" }),
        P("limit", "uint", { example: "10", max: 1000 })] },
    { group: "Database", login: "database", method: "get_witness_count",
      tier: TIERS.read, src: "database_api.hpp:1151",
      desc: "Total witnesses (plain int).",
      params: [] },
    { group: "Database", login: "database", method: "get_committee_members",
      tier: TIERS.read, src: "database_api.hpp:1164",
      desc: "Committee members by ID list.",
      params: [P("ids", "strlist", { example: '["1.5.0"]' })] },
    { group: "Database", login: "database", method: "get_committee_member_by_account",
      tier: TIERS.read, src: "database_api.hpp:1172",
      desc: "Committee record for an account (or null).",
      params: [P("account", "string", { example: "committee-account" })] },
    { group: "Database", login: "database", method: "lookup_committee_member_accounts",
      tier: TIERS.read, src: "database_api.hpp:1181",
      desc: "Committee names from a lower bound (prefix scan).",
      params: [P("lower_bound_name", "string", { example: "" }),
        P("limit", "uint", { example: "10", max: 1000 })] },
    { group: "Database", login: "database", method: "get_committee_count",
      tier: TIERS.read, src: "database_api.hpp:1188",
      desc: "Total committee members (plain int).",
      params: [] },
    { group: "Database", login: "database", method: "get_all_workers",
      tier: TIERS.read, src: "database_api.hpp:1201",
      desc: "All workers (blank = both live and expired).",
      params: [P("is_expired", "bool", { required: false, example: "",
        hint: "true/false, blank = all." })] },
    { group: "Database", login: "database", method: "get_workers_by_account",
      tier: TIERS.read, src: "database_api.hpp:1208",
      desc: "Workers owned by an account.",
      params: [P("account", "string", { example: "committee-account" })] },
    { group: "Database", login: "database", method: "get_worker_count",
      tier: TIERS.read, src: "database_api.hpp:1213",
      desc: "Total workers (plain int).",
      params: [] },
    { group: "Database", login: "database", method: "lookup_vote_ids",
      tier: TIERS.read, src: "database_api.hpp:1233",
      desc: "Vote ids to objects (JSON array like [\"1:5\"]).",
      params: [P("votes", "json", { example: '["1:5"]',
        hint: "JSON array of vote ids." })] },
    { group: "Database", login: "database", method: "get_transaction_hex",
      tier: TIERS.read, src: "database_api.hpp:1244",
      desc: "Hex dump of a signed transaction (paste full tx JSON).",
      params: [P("trx", "json", { example: "{\"ref_block_num\":1,\"ref_block_prefix\":1,\"expiration\":\"2026-01-01T00:00:00\",\"signatures\":[],\"operations\":[]}" })] },
    { group: "Database", login: "database", method: "get_transaction_hex_without_sig",
      tier: TIERS.read, src: "database_api.hpp:1251",
      desc: "Hex dump without signatures (paste unsigned tx JSON).",
      params: [P("trx", "json", { example: "{\"ref_block_num\":1,\"ref_block_prefix\":1,\"expiration\":\"2026-01-01T00:00:00\",\"operations\":[]}" })] },
    { group: "Database", login: "database", method: "get_required_signatures",
      tier: TIERS.read, src: "database_api.hpp:1262",
      desc: "Minimal signing keys for a tx + available keys.",
      params: [P("trx", "json", { example: "{\"ref_block_num\":1,\"ref_block_prefix\":1,\"expiration\":\"2026-01-01T00:00:00\",\"signatures\":[],\"operations\":[]}" }),
        P("available_keys", "strlist", { example: '["BTS6..."]' })] },
    { group: "Database", login: "database", method: "get_potential_signatures",
      tier: TIERS.read, src: "database_api.hpp:1273",
      desc: "All keys that could sign a transaction.",
      params: [P("trx", "json", { example: "{\"ref_block_num\":1,\"ref_block_prefix\":1,\"expiration\":\"2026-01-01T00:00:00\",\"signatures\":[],\"operations\":[]}" })] },
    { group: "Database", login: "database", method: "get_potential_address_signatures",
      tier: TIERS.read, src: "database_api.hpp:1281",
      desc: "All addresses that could sign a transaction.",
      params: [P("trx", "json", { example: "{\"ref_block_num\":1,\"ref_block_prefix\":1,\"expiration\":\"2026-01-01T00:00:00\",\"signatures\":[],\"operations\":[]}" })] },
    { group: "Database", login: "database", method: "get_required_fees",
      tier: TIERS.fee, src: "database_api.hpp:1313",
      desc: "Fee preview for operations (the ONLY fee source — #3720). Paste operations JSON.",
      params: [P("ops", "json", { example: "[[0,{\"from\":\"1.2.0\",\"to\":\"1.2.5\",\"amount\":{\"amount\":\"100000\",\"asset_id\":\"1.3.0\"}}]]",
        hint: "JSON array of [op_id, op_data] pairs." }),
        P("asset_id", "string", { example: "1.3.0" })] },
    { group: "Database", login: "database", method: "get_proposed_transactions",
      tier: TIERS.read, src: "database_api.hpp:1326",
      desc: "Proposals an account must approve (1.10.x).",
      params: [P("account", "string", { example: "committee-account" })] },
    { group: "Database", login: "database", method: "get_blinded_balances",
      tier: TIERS.read, src: "database_api.hpp:1337",
      desc: "Blinded balances for commitments (JSON array of hex).",
      params: [P("commitments", "strlist", { example: '["02ab..."]' })] },
    { group: "Database", login: "database", method: "get_withdraw_permissions_by_giver",
      tier: TIERS.read, src: "database_api.hpp:1352",
      desc: "Direct-debit permissions granted BY an account.",
      params: [P("account", "string", { example: "committee-account" }),
        P("start", "string", { example: "1.12.0" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "get_withdraw_permissions_by_recipient",
      tier: TIERS.read, src: "database_api.hpp:1365",
      desc: "Direct-debit permissions granted TO an account.",
      params: [P("account", "string", { example: "committee-account" }),
        P("start", "string", { example: "1.12.0" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "get_htlc",
      tier: TIERS.read, src: "database_api.hpp:1381",
      desc: "One HTLC object by id (1.16.x).",
      params: [P("id", "string", { example: "1.16.0" }),
        P("subscribe", "bool", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_htlc_by_from",
      tier: TIERS.read, src: "database_api.hpp:1391",
      desc: "Live HTLCs sent FROM an account.",
      params: [P("account", "string", { example: "committee-account" }),
        P("start", "string", { example: "1.16.0" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "get_htlc_by_to",
      tier: TIERS.read, src: "database_api.hpp:1403",
      desc: "Live HTLCs sent TO an account.",
      params: [P("account", "string", { example: "committee-account" }),
        P("start", "string", { example: "1.16.0" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "list_htlcs",
      tier: TIERS.read, src: "database_api.hpp:1414",
      desc: "HTLCs from a start id (1.16.x scan).",
      params: [P("start", "string", { example: "1.16.0" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Database", login: "database", method: "list_tickets",
      tier: TIERS.read, src: "database_api.hpp:1435",
      desc: "Tickets, paged (blank = first page).",
      params: [P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" })] },
    { group: "Database", login: "database", method: "get_tickets_by_account",
      tier: TIERS.read, src: "database_api.hpp:1455",
      desc: "Tickets owned by an account.",
      params: [P("account", "string", { example: "committee-account" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" })] },
    { group: "History", login: "history", method: "get_account_history",
      tier: TIERS.read, src: "api.hpp:89",
      desc: "Account history page (most-recent-first).",
      params: [P("account", "string", { example: "1.2.0" }),
        P("stop", "string", { example: "1.11.0",
          hint: "Stop object ID (1.11.0 = genesis)." }),
        P("limit", "uint", { example: "10", max: 100 }),
        P("start", "string", { example: "1.11.0",
          hint: "Start object ID (1.11.0 = latest)." })] },
    { group: "History", login: "history", method: "get_account_history_by_time",
      tier: TIERS.read, src: "api.hpp:112",
      desc: "Account history before a UTC time (blank time = now).",
      params: [P("account", "string", { example: "1.2.0" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start", "string", { required: false, example: "",
          hint: "UTC time, blank = now." })] },
    { group: "History", login: "history", method: "get_account_history_by_operations",
      tier: TIERS.read, src: "api.hpp:128",
      desc: "Account history filtered to op types (JSON int array).",
      params: [P("account", "string", { example: "1.2.0" }),
        P("operation_types", "json", { example: "[0,1]",
          hint: "JSON array of op ids." }),
        P("start", "uint", { example: "0" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "History", login: "history", method: "get_account_history_operations",
      tier: TIERS.read, src: "api.hpp:146",
      desc: "Account history for one op type between two history ids.",
      params: [P("account", "string", { example: "1.2.0" }),
        P("operation_type", "int", { example: "0" }),
        P("start", "string", { required: false, example: "1.11.0" }),
        P("stop", "string", { required: false, example: "1.11.0" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "History", login: "history", method: "get_relative_account_history",
      tier: TIERS.read, src: "api.hpp:167",
      desc: "Account history by sequence offset.",
      params: [P("account", "string", { example: "1.2.0" }),
        P("stop", "uint", { example: "0" }),
        P("limit", "uint", { example: "10", max: 100 }),
        P("start", "uint", { example: "0", hint: "0 = most recent." })] },
    { group: "History", login: "history", method: "get_block_operation_history",
      tier: TIERS.read, src: "api.hpp:186",
      desc: "Ops in one block (blank trx = whole block).",
      params: [P("block_num", "uint", { example: "100916767" }),
        P("trx_in_block", "uint", { required: false, example: "" })] },
    { group: "History", login: "history", method: "get_block_operations_by_time",
      tier: TIERS.read, src: "api.hpp:202",
      desc: "Ops in the most recent non-empty block at/before a time.",
      params: [P("start", "string", { required: false, example: "",
        hint: "UTC time, blank = latest." })] },
    { group: "History", login: "history", method: "get_fill_order_history",
      tier: TIERS.read, src: "api.hpp:212",
      desc: "Recent fills in a market (order executions).",
      params: [P("a", "string", { example: "BTS" }),
        P("b", "string", { example: "USD" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "History", login: "history", method: "get_market_history",
      tier: TIERS.read, src: "api.hpp:229",
      desc: "OHLCV buckets for a market in a UTC range.",
      params: [P("a", "string", { example: "BTS" }),
        P("b", "string", { example: "USD" }),
        P("bucket_seconds", "uint", { example: "3600",
          hint: "Must be a supported bucket." }),
        P("start", "string", { example: "2026-01-01T00:00:00" }),
        P("end", "string", { example: "2026-10-01T00:00:00" })] },
    { group: "History", login: "history", method: "get_market_history_buckets",
      tier: TIERS.read, src: "api.hpp:239",
      desc: "Supported OHLCV bucket lengths (seconds).",
      params: [] },
    { group: "History", login: "history", method: "get_liquidity_pool_history",
      tier: TIERS.read, src: "api.hpp:266",
      desc: "Pool ops before a UTC time (59 create … 63 swap).",
      params: [P("pool_id", "string", { example: "1.19.0" }),
        P("start", "string", { required: false, example: "" }),
        P("stop", "string", { required: false, example: "" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("operation_type", "int", { required: false, example: "",
          hint: "59-63, blank = all." })] },
    { group: "History", login: "history", method: "get_liquidity_pool_history_by_sequence",
      tier: TIERS.read, src: "api.hpp:295",
      desc: "Pool ops by sequence pointer (for same-second overflow).",
      params: [P("pool_id", "string", { example: "1.19.0" }),
        P("start", "uint", { required: false, example: "" }),
        P("stop", "string", { required: false, example: "" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("operation_type", "int", { required: false, example: "" })] },
    { group: "Network", login: "network_node", method: "get_info",
      tier: TIERS.read, src: "api.hpp:401",
      desc: "P2P network info (often restricted on public nodes).",
      params: [] },
    { group: "Network", login: "network_node", method: "get_connected_peers",
      tier: TIERS.read, src: "api.hpp:412",
      desc: "Peer list (often restricted on public nodes).",
      params: [] },
    { group: "Network", login: "network_node", method: "get_potential_peers",
      tier: TIERS.read, src: "api.hpp:430",
      desc: "Known potential peers (often restricted on public nodes).",
      params: [] },
    { group: "Network", login: "network_broadcast", method: "broadcast_transaction",
      tier: TIERS.broadcast, src: "api.hpp:352",
      desc: "Broadcast a SIGNED transaction. Paste full signed-tx JSON; needs unlock + confirm.",
      params: [P("trx", "json", { example: "{\"ref_block_num\":1,\"ref_block_prefix\":1,\"expiration\":\"2026-01-01T00:00:00\",\"signatures\":[],\"operations\":[]}",
        hint: "Full signed transaction object." })] },
    { group: "Block", login: "block", method: "get_blocks",
      tier: TIERS.read, src: "api.hpp:320",
      desc: "Range of signed blocks (bounded — keep the window small).",
      params: [P("block_num_from", "uint", { example: "100916767" }),
        P("block_num_to", "uint", { example: "100916768" })] },
    { group: "Asset", login: "asset", method: "get_asset_holders",
      tier: TIERS.read, src: "api.hpp:573",
      desc: "Holders of an asset, paged (start = offset).",
      params: [P("asset", "string", { example: "BTS" }),
        P("start", "uint", { example: "0" }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Asset", login: "asset", method: "get_asset_holders_count",
      tier: TIERS.read, src: "api.hpp:581",
      desc: "Holder count for an asset (plain int).",
      params: [P("asset", "string", { example: "BTS" })] },
    { group: "Asset", login: "asset", method: "get_all_asset_holders",
      tier: TIERS.read, src: "api.hpp:587",
      desc: "All asset holder summaries (heavy — may time out).",
      params: [] },
    { group: "Orders", login: "orders", method: "get_tracked_groups",
      tier: TIERS.read, src: "api.hpp:623",
      desc: "Tracked grouping intervals (seconds).",
      params: [] },
    { group: "Orders", login: "orders", method: "get_grouped_limit_orders",
      tier: TIERS.read, src: "api.hpp:636",
      desc: "Grouped limit orders in a market (best price first).",
      params: [P("base_asset", "string", { example: "BTS" }),
        P("quote_asset", "string", { example: "USD" }),
        P("group", "uint", { example: "10" }),
        P("start", "json", { required: false, example: "",
          hint: "Price object or blank." }),
        P("limit", "uint", { example: "10", max: 100 })] },
    { group: "Custom", login: "custom_operations", method: "get_storage_info",
      tier: TIERS.read, src: "api.hpp:683",
      desc: "Custom-plugin stored objects (trollbox/forum store; all optional).",
      params: [P("account", "string", { required: false, example: "" }),
        P("catalog", "string", { required: false, example: "" }),
        P("key", "string", { required: false, example: "" }),
        P("limit", "uint", { required: false, example: "10", max: 100 }),
        P("start_id", "string", { required: false, example: "" })] },
    { group: "Debug", login: "debug", method: "(login probe)",
      tier: TIERS.debug, src: "api.hpp (no debug_api class — probe only)",
      desc: "Availability probe: attempts the debug login most public nodes reject. The rejection IS the result.",
      params: [] }
  ];

  /* byMethod: find one entry by method name + login. Params: method, login.
   * Returns the entry or null. Fails: never throws. */
  function byMethod(method, login) {
    for (var i = 0; i < METHODS.length; i++) {
      if (METHODS[i].method === method && METHODS[i].login === login) return METHODS[i];
    }
    for (var j = 0; j < METHODS.length; j++) {
      if (METHODS[j].method === method) return METHODS[j];
    }
    return null;
  }

  /* defaults: example values per param (deep-link/prefill helper).
   * Params: entry. Returns a string array aligned with entry.params. */
  function defaults(entry) {
    return (entry.params || []).map(function (p) { return p.example || ""; });
  }

  /* coerce: curated strings -> typed RPC params. Params: entry, values
   * (string array aligned with entry.params). Returns the typed array.
   * Fails: throws a named Error (uint/int/bool/json/strlist shape problems).
   * Optional blanks coerce to null (the node's "omitted" sentinel). */
  function coerce(entry, values) {
    var out = [];
    var ps = entry.params || [];
    for (var i = 0; i < ps.length; i++) {
      var p = ps[i];
      var v = (values && i < values.length && typeof values[i] === "string") ? values[i] : "";
      if ((!v || !v.length) && p.required) throw new Error("missing: " + p.name);
      if (!v || !v.length) {
        out.push(null);
        continue;
      }
      if (p.type === "uint") {
        if (!/^[0-9]+$/.test(v)) throw new Error("bad uint: " + p.name);
        var n = parseInt(v, 10);
        if (p.max !== null && n > p.max) throw new Error("over max " + p.max + ": " + p.name);
        out.push(n);
      } else if (p.type === "int") {
        if (!/^-?[0-9]+$/.test(v)) throw new Error("bad int: " + p.name);
        var k = parseInt(v, 10);
        if (p.max !== null && k > p.max) throw new Error("over max " + p.max + ": " + p.name);
        out.push(k);
      } else if (p.type === "bool") {
        if (v !== "true" && v !== "false") throw new Error("bad bool: " + p.name);
        out.push(v === "true");
      } else if (p.type === "json" || p.type === "strlist") {
        var parsed;
        try { parsed = JSON.parse(v); } catch (e) { throw new Error("bad JSON: " + p.name); }
        if (p.type === "strlist") {
          if (!Array.isArray(parsed)) throw new Error("need array: " + p.name);
        }
        out.push(parsed);
      } else {
        out.push(v);
      }
    }
    return out;
  }

  /* run: execute one catalog entry on the shared socket. Params: entry,
   * values (curated string array). Returns a Promise for the raw result.
   * Fails: rejects with the node's error (or not-connected/timeout). The
   * debug probe resolves its login attempt — rejection surfaces verbatim. */
  function run(entry, values) {
    var params = coerce(entry, values);
    if (entry.login === "debug" && entry.method === "(login probe)") {
      return Chain.call(1, "debug", []);
    }
    return Chain.call(1, entry.login, []).then(function (apiId) {
      return Chain.call(apiId, entry.method, params);
    });
  }

  return { GROUPS: GROUPS, TIERS: TIERS, METHODS: METHODS,
    byMethod: byMethod, defaults: defaults, coerce: coerce, run: run };
})();

if (typeof module !== "undefined") { module.exports = ApiLab; }
