/* Tier 2 signing gate: SW request router (P1+P2).
 * Owns: dApp + wallet-self request handling (getChainId/getAccount/
 *   requestSignature), Bridge validation, session-persisted per-origin rate
 *   limits, approval intents (journal + 60s alarm deadline + one-at-a-time),
 *   SW-side unlock (Wallet + chrome backend, persisted backoff), op
 *   enrichment (asset precisions/symbols via the SW Chain for human amounts),
 *   SW-side sign (Tx.sign vs the SW Chain) + ack-based broadcast, session
 *   wipe on lock, fail-closed startup (deny journaled pendings).
 * Trust boundaries: page-claimed origin is IGNORED — origin comes from the
 *   content relay's platform-provided event.origin, or sender.tab.url when
 *   present. Unsigned txs are shape-gated (Bridge.isValidUnsignedTx) before
 *   any approval opens; ops are re-matched to the approval receipt before
 *   signing (no blind signing — same rule as the signMessage refusal).
 *   Passwords transit SW messages only (same extension origin, never
 *   stored); keys live in chrome.storage.session (MV2: background-page
 *   memory via session.js fallback) and are wiped by the lock path.
 * Consumes: Bridge (validators/protocol), SessionVault (storage),
 *   Wallet (+ chrome backend), Chain (SW-owned socket), Tx/Tx._ser,
 *   Format (amount display), chrome.alarms/runtime/storage/tabs.
 *   No DOM. Globals/side effects: global Gate only; sockets/alarms/intents.
 *   module.exports for node tests (chrome/Chain/etc. stubbed by the test).
 * Created by: extension Tier 2 build (P1+P2 batch).
 */
var Gate = (function () {
  "use strict";

  /* Op names: chain fact (order + names per protocol/operations.hpp),
   * labels via tooling/gen_tier2_opnames.py from the open-graphene
   * machine spec (78 ops, tags 0-77), human-label convention matching
   * vanilla/js/views/account-ui.js OP_LABELS. Reference-consulted,
   * embedded (never a dependency). Rerun the script to re-verify. */
/* Generated by tooling/gen_tier2_opnames.py from the open-graphene
 * machine spec (78 ops, tags 0-77). Human-label convention matches
 * vanilla/js/views/account-ui.js OP_LABELS. */
var OP_NAMES = {
  0: "Transfer",
  1: "Limit order create",
  2: "Limit order cancel",
  3: "Call order update",
  4: "Fill order",
  5: "Account create",
  6: "Account update",
  7: "Account whitelist",
  8: "Account upgrade",
  9: "Account transfer",
  10: "Asset create",
  11: "Asset update",
  12: "Asset update bitasset",
  13: "Asset update feed producers",
  14: "Asset issue",
  15: "Asset reserve",
  16: "Asset fund fee pool",
  17: "Asset settle",
  18: "Asset global settle",
  19: "Asset publish feed",
  20: "Witness create",
  21: "Witness update",
  22: "Proposal create",
  23: "Proposal update",
  24: "Proposal delete",
  25: "Withdraw permission create",
  26: "Withdraw permission update",
  27: "Withdraw permission claim",
  28: "Withdraw permission delete",
  29: "Committee member create",
  30: "Committee member update",
  31: "Committee member update global parameters",
  32: "Vesting balance create",
  33: "Vesting balance withdraw",
  34: "Worker create",
  35: "Custom",
  36: "Assert",
  37: "Balance claim",
  38: "Override transfer",
  39: "Transfer to blind",
  40: "Blind transfer",
  41: "Transfer from blind",
  42: "Asset settle cancel",
  43: "Asset claim fees",
  44: "Fba distribute",
  45: "Bid collateral",
  46: "Execute bid",
  47: "Asset claim pool",
  48: "Asset update issuer",
  49: "Htlc create",
  50: "Htlc redeem",
  51: "Htlc redeemed",
  52: "Htlc extend",
  53: "Htlc refund",
  54: "Custom authority create",
  55: "Custom authority update",
  56: "Custom authority delete",
  57: "Ticket create",
  58: "Ticket update",
  59: "Liquidity pool create",
  60: "Liquidity pool delete",
  61: "Liquidity pool deposit",
  62: "Liquidity pool withdraw",
  63: "Liquidity pool exchange",
  64: "Samet fund create",
  65: "Samet fund delete",
  66: "Samet fund update",
  67: "Samet fund borrow",
  68: "Samet fund repay",
  69: "Credit offer create",
  70: "Credit offer delete",
  71: "Credit offer update",
  72: "Credit offer accept",
  73: "Credit deal repay",
  74: "Credit deal expired",
  75: "Liquidity pool update",
  76: "Credit deal update",
  77: "Limit order update",
};

  /* Approval deadline alarm prefix (per-intent alarm: vb-approve-<id>). */
  var ALARM_PREFIX = "vb-approve-";
  /* Session keys for the one-at-a-time pending intent id. */
  var K_PENDING = "vb-pending-intent";

  /* ext: browser vs chrome namespace, or null outside extensions. */
  function ext() {
    try {
      if (typeof browser !== "undefined" && browser && browser.runtime) return browser;
      if (typeof chrome !== "undefined" && chrome && chrome.runtime) return chrome;
    } catch (e) { /* null below */ }
    return null;
  }

  /* opName: human label for an op id; unknown ids stay identifiable
   * (never blank, never guessed-wrong — "Operation 81" is honest). */
  function opName(id) {
    try {
      if (typeof id === "number" && Object.prototype.hasOwnProperty.call(OP_NAMES, id)) {
        return OP_NAMES[id];
      }
    } catch (e) { /* fallback below */ }
    return "Operation " + String(id);
  }

  /* senderOrigin: trustworthy origin for an onMessage sender. Prefers the
   * platform-provided sender.tab.url (unforgeable); falls back to the
   * relay-attached msg.origin (content script copies postMessage
   * event.origin, also platform-provided). Page-claimed fields inside
   * payload are never consulted. Returns "" when neither exists. */
  function senderOrigin(msg, sender) {
    try {
      if (sender && sender.tab && typeof sender.tab.url === "string" && sender.tab.url) {
        var m = /^(https:\/\/[^/]+)/.exec(sender.tab.url);
        if (m) return m[1];
      }
    } catch (e) { /* fallback below */ }
    try {
      if (msg && typeof msg.origin === "string" && msg.origin) return msg.origin;
    } catch (e) { /* empty below */ }
    return "";
  }

  /* isExtensionPage: true when the message came from one of our own
   * extension pages (approval / wallet). Params: sender. Trusts the
   * platform-provided sender only (url scheme + own extension id when
   * available — id check skipped when the runtime omits it, scheme still
   * gates: only chrome-extension:// pages pass). */
  function isExtensionPage(sender) {
    try {
      var url = sender && sender.tab && sender.tab.url;
      if (typeof url !== "string" || url.indexOf("chrome-extension://") !== 0 &&
          url.indexOf("moz-extension://") !== 0) {
        /* No tab (e.g. direct runtime message from an extension page):
         * sender.id must equal our own runtime id. */
        var e = ext();
        var ownId = null;
        try { ownId = e && e.runtime && e.runtime.id ? String(e.runtime.id) : null; } catch (x) { ownId = null; }
        var sid = sender && sender.id ? String(sender.id) : null;
        if (ownId && sid) return ownId === sid;
        return false;
      }
      return true;
    } catch (e) { return false; }
  }

  /* readSettings: active {network, activeNode} from the persisted envelope
   * (same key + shape as Store, parsed directly because Store is sync and
   * chrome.storage is async). Falls back to mainnet defaults. Never throws. */
  function readSettings() {
    var fb = { network: "mainnet", activeNode: "wss://api.bitshares.dev/ws" };
    try {
      if (typeof SessionVault === "undefined" || !SessionVault) return fb;
      return SessionVault.localGet(["bts-vanilla-settings-v1"]).then(function (items) {
        try {
          var raw = items ? items["bts-vanilla-settings-v1"] : null;
          if (!raw) return fb;
          var s = JSON.parse(raw);
          var out = { network: "mainnet", activeNode: fb.activeNode };
          if (s && (s.network === "mainnet" || s.network === "testnet")) out.network = s.network;
          if (s && typeof s.activeNode === "string" && s.activeNode) out.activeNode = s.activeNode;
          return out;
        } catch (e) { return fb; }
      }).catch(function () { return fb; });
    } catch (e) { return Promise.resolve(fb); }
  }

  /* ensureChain: SW-owned Chain connected to the active node (idempotent —
   * connected/ connecting states reuse the socket). Resolves the chainId.
   * Rejects when no Chain module or connection fails. */
  function ensureChain() {
    try {
      if (typeof Chain === "undefined" || !Chain || typeof Chain.connect !== "function") {
        return Promise.reject(new Error("chain module missing in SW"));
      }
      var st = null;
      try { st = Chain.status(); } catch (e) { st = null; }
      if (st && (st.state === "open" || st.state === "connecting") && st.chainId) {
        return Promise.resolve(st.chainId);
      }
      return readSettings().then(function (s) {
        return Chain.connect(s.activeNode).then(function (r) { return r.chainId; });
      });
    } catch (e) { return Promise.reject(e); }
  }

  /* collectAssetIds: walk an op body for {amount, asset_id} shapes (fee
   * included) and return unique 1.3.x ids. Pure JSON walk, never throws. */
  function collectAssetIds(body) {
    var out = [], seen = {};
    try {
      (function walk(v) {
        if (!v || typeof v !== "object") return;
        if (Array.isArray(v)) { for (var i = 0; i < v.length; i++) walk(v[i]); return; }
        var ks = Object.keys(v);
        if (typeof v.amount !== "undefined" && typeof v.asset_id === "string" &&
            /^1\.3\.\d+$/.test(v.asset_id) && /^-?\d+$/.test(String(v.amount))) {
          if (!seen[v.asset_id]) { seen[v.asset_id] = 1; out.push(v.asset_id); }
        }
        for (var k = 0; k < ks.length; k++) walk(v[ks[k]]);
      })(body);
    } catch (e) { /* partial list stands */ }
    return out;
  }

  /* humanizeAmounts: attach display strings to amount shapes in an op body.
   * Params: body (op data), meta {id->{symbol,precision}}. Returns a fields
   * array [{k, v}] where amount shapes render "1.5000 BTS (raw 150000)" and
   * fee renders likewise; nested objects/arrays render exact JSON; scalars
   * render verbatim. Never throws (worst case: everything raw). */
  function humanizeFields(body, meta) {
    var fields = [];
    try {
      var keys = (body && typeof body === "object" && !Array.isArray(body)) ? Object.keys(body) : [];
      keys.forEach(function (k) {
        var v = body[k];
        try {
          if (v && typeof v === "object" && !Array.isArray(v) &&
              typeof v.asset_id === "string" && v.amount !== undefined &&
              meta && meta[v.asset_id]) {
            var m = meta[v.asset_id];
            var disp = v.amount;
            try {
              if (typeof Format !== "undefined" && Format && typeof Format.formatAmount === "function" &&
                  typeof m.precision === "number" && /^-?\d+$/.test(String(v.amount))) {
                disp = Format.formatAmount(String(v.amount), m.precision) + " " + (m.symbol || v.asset_id);
              }
            } catch (e) { disp = String(v.amount); }
            fields.push({ k: k, v: disp + " (raw " + String(v.amount) + ")" });
          } else if (v && typeof v === "object") {
            fields.push({ k: k, v: JSON.stringify(v) });
          } else {
            fields.push({ k: k, v: String(v) });
          }
        } catch (e) { fields.push({ k: k, v: String(v) }); }
      });
    } catch (e) { /* fields stand partial */ }
    return fields;
  }

  /* enrichUnsigned: resolve asset metadata for every amount shape in the
   * unsigned tx and build the approval-ready structure:
   * {ops: [{id, name, fields}], feeAssetNote}. Requires the SW Chain open
   * (ensureChain first). Unknown assets render raw, never blank. */
  function enrichUnsigned(unsigned) {
    var ids = [], seen = {};
    (unsigned.operations || []).forEach(function (op) {
      collectAssetIds(op[1]).forEach(function (id) {
        if (!seen[id]) { seen[id] = 1; ids.push(id); }
      });
    });
    function metaFor(list) {
      var meta = {};
      (list || []).forEach(function (a) {
        if (a && typeof a.id === "string") {
          meta[a.id] = {
            symbol: (typeof a.symbol === "string" && a.symbol) ? a.symbol : a.id,
            precision: (typeof a.precision === "number") ? a.precision : null
          };
        }
      });
      return meta;
    }
    function build(meta) {
      return {
        ops: (unsigned.operations || []).map(function (op) {
          return { id: op[0], name: opName(op[0]), fields: humanizeFields(op[1], meta) };
        })
      };
    }
    if (!ids.length) return Promise.resolve(build({}));
    var dbId = null;
    return Chain.db().then(function (id) {
      dbId = id;
      return Chain.call(dbId, "get_objects", [ids]);
    }).then(function (rows) {
      return build(metaFor(rows));
    }).catch(function () { return build({}); });
  }

  /* swBroadcast: ack-based broadcast from the SW (no history-poll inclusion
   * proof — polls are transfer-specific (op 0) and would wrongly fail valid
   * non-transfer broadcasts after 30s. The dApp verifies inclusion via
   * history like any client; wallet-self flows run their existing prove
   * loops page-side on the returned ack). Resolves {via, headBefore}.
   * Rejects with the node's error (sendRejected safe-retry flag preserved). */
  function swBroadcast(signedTx) {
    var netId = null, headBefore = 0, via = "broadcast_transaction_with_callback";
    return Chain.net().then(function (id) {
      netId = id;
      return Chain.db().then(function (dbId) {
        return Chain.call(dbId, "get_dynamic_global_properties", []).then(function (p) {
          try { headBefore = (p && p.head_block_number) || 0; } catch (e) { headBefore = 0; }
        }).catch(function () { headBefore = 0; });
      });
    }).then(function () {
      var callbackId = (Math.random() * 4294967296) >>> 0;
      return Chain.call(netId, "broadcast_transaction_with_callback", [callbackId, signedTx]).catch(function (e) {
        via = "broadcast_transaction";
        return Chain.call(netId, "broadcast_transaction", [signedTx]).catch(function (e2) {
          e2.sendRejected = true;
          throw e2;
        });
      });
    }).then(function () { return { via: via + "+sw-ack", headBefore: headBefore }; });
  }

  /* getJournal/setJournal: pending-intent journal in session storage
   * (survives SW restarts so startup can deny them fail-closed). */
  function getJournal() {
    try {
      return SessionVault.sessionGet([SessionVault.K_INTENTS]).then(function (items) {
        var j = items ? items[SessionVault.K_INTENTS] : null;
        return (j && typeof j === "object" && !Array.isArray(j)) ? j : {};
      }).catch(function () { return {}; });
    } catch (e) { return Promise.resolve({}); }
  }

  function setJournal(j) {
    try {
      var o = {};
      o[SessionVault.K_INTENTS] = j || {};
      return SessionVault.sessionSet(o).catch(function () { return true; });
    } catch (e) { return Promise.resolve(true); }
  }

  /* getAllowlist: persistent per-origin grants (fail-safe: missing store
   * reads as no grants — every request prompts). */
  function getAllowlist() {
    try {
      return SessionVault.localGet([SessionVault.K_ALLOWLIST]).then(function (items) {
        var a = items ? items[SessionVault.K_ALLOWLIST] : null;
        return (a && typeof a === "object" && !Array.isArray(a)) ? a : {};
      }).catch(function () { return {}; });
    } catch (e) { return Promise.resolve({}); }
  }

  function setAllowlist(a) {
    try {
      var o = {};
      o[SessionVault.K_ALLOWLIST] = a || {};
      return SessionVault.localSet(o).catch(function () { return true; });
    } catch (e) { return Promise.resolve(true); }
  }

  /* openApproval: one approval tab for an intent (tabs.create needs no
   * special permission for extension URLs). Resolves the tab id (null when
   * tabs are unavailable — the intent still stands for the options-page
   * flow; the requester polls nothing, the 60s alarm is the backstop). */
  function openApproval(intentId) {
    try {
      var e = ext();
      if (!e || !e.tabs || typeof e.tabs.create !== "function") return Promise.resolve(null);
      var url = null;
      try { url = e.runtime.getURL("approval/approval.html#" + encodeURIComponent(intentId)); }
      catch (x) { url = "approval/approval.html#" + encodeURIComponent(intentId); }
      return new Promise(function (resolve) {
        try {
          e.tabs.create({ url: url }, function (tab) {
            resolve(tab && tab.id !== undefined ? tab.id : null);
          });
        } catch (x) { resolve(null); }
      });
    } catch (x) { return Promise.resolve(null); }
  }

  /* armDeadline: 60s alarm backstop for an intent (alarms survive SW
   * sleep, unlike setTimeout — the same reason vb-lock uses alarms).
   * Firing denies the intent; the approval page's own countdown is display
   * only. Never throws. */
  function armDeadline(intentId) {
    try {
      var e = ext();
      if (!e || !e.alarms || typeof e.alarms.create !== "function") return;
      var ms = 60000;
      try {
        if (typeof Bridge !== "undefined" && Bridge && Bridge.APPROVAL_TIMEOUT_MS) {
          ms = Bridge.APPROVAL_TIMEOUT_MS;
        }
      } catch (x) { /* default stands */ }
      e.alarms.create(ALARM_PREFIX + intentId, { when: Date.now() + ms });
    } catch (x) { /* requester timeout (65s ceiling) is the backstop */ }
  }

  function clearDeadline(intentId) {
    try {
      var e = ext();
      if (e && e.alarms && typeof e.alarms.clear === "function") {
        e.alarms.clear(ALARM_PREFIX + intentId, function () {});
      }
    } catch (x) { /* alarm fires into a settled intent: no-op */ }
  }

  /* settleIntent: mark resolved/denied, clear deadline, drop pending slot.
   * Params: id, patch {status, error?, proof?}. Resolves the journal. */
  function settleIntent(id, patch) {
    return getJournal().then(function (j) {
      if (j[id]) {
        j[id].status = (patch && patch.status) || "denied";
        if (patch && patch.error !== undefined) j[id].error = String(patch.error);
        if (patch && patch.proof !== undefined) j[id].proof = patch.proof;
        j[id].settledAt = Date.now();
      }
      clearDeadline(id);
      return SessionVault.sessionRemove([K_PENDING]).catch(function () {}).then(function () {
        return setJournal(j);
      });
    });
  }

  /* denyPending: startup fail-closed — every journaled pending intent is
   * denied (an SW restart must never leave a request hanging as approved).
   * Resolves the denied count. */
  function denyPending() {
    return getJournal().then(function (j) {
      var ids = Object.keys(j).filter(function (id) {
        return j[id] && j[id].status === "pending";
      });
      ids.forEach(function (id) {
        j[id].status = "denied";
        j[id].error = "service worker restarted during approval";
        j[id].settledAt = Date.now();
        clearDeadline(id);
      });
      return setJournal(j).then(function () {
        return SessionVault.sessionRemove([K_PENDING]).catch(function () {});
      }).then(function () { return ids.length; });
    }).catch(function () { return 0; });
  }

  /* wipeSession: lock path — drop session keys + meta, deny pendings,
   * keep the allowlist (grants are explicit user choices, revoked only in
   * Settings). Resolves true. */
  function wipeSession() {
    try {
      return SessionVault.sessionRemove(
        [SessionVault.K_KEYS, SessionVault.K_META, K_PENDING]
      ).catch(function () {}).then(function () { return denyPending(); })
        .then(function () { return true; });
    } catch (e) { return Promise.resolve(true); }
  }

  /* readSessionKeys: session key slots (null when locked). Shape:
   * {active:{wif,pub}, owner:{wif,pub}?, memo:{wif,pub}?} — every slot the
   * envelope carried (single trust domain, single session). */
  function readSessionKeys() {
    try {
      return SessionVault.sessionGet([SessionVault.K_KEYS]).then(function (items) {
        var k = items ? items[SessionVault.K_KEYS] : null;
        if (k && typeof k === "object" && k.active && typeof k.active.wif === "string") return k;
        return null;
      }).catch(function () { return null; });
    } catch (e) { return Promise.resolve(null); }
  }

  /* unlockSession: decrypt the envelope (Wallet + chrome backend, persisted
   * backoff intact) and store ALL key slots in the session vault, then lock
   * the Wallet module to wipe SW-heap copies (session storage is the single
   * holder from here on). Params: password string. Resolves {pub} (active).
   * Rejects wrong-password / locked-out / no-wallet verbatim. */
  function unlockSession(password) {
    try {
      if (typeof password !== "string" || !password) {
        return Promise.reject(new Error("password required"));
      }
      if (typeof Wallet === "undefined" || !Wallet || typeof Wallet.unlock !== "function") {
        return Promise.reject(new Error("wallet module missing in SW"));
      }
      return Wallet.unlock(password).then(function (keys) {
        var slots = {};
        ["active", "owner", "memo"].forEach(function (slot) {
          try {
            if (keys && keys[slot] && typeof keys[slot].wif === "string") {
              slots[slot] = { wif: keys[slot].wif, pub: keys[slot].pub || null };
            }
          } catch (e) { /* slot skipped */ }
        });
        if (!slots.active) throw new Error("envelope has no active key");
        var o = {};
        o[SessionVault.K_KEYS] = slots;
        var m = {};
        m[SessionVault.K_META] = { unlockedAt: Date.now() };
        o[SessionVault.K_META] = m[SessionVault.K_META];
        return SessionVault.sessionSet(o).then(function () {
          try { if (typeof Wallet.lock === "function") Wallet.lock(); } catch (e) { /* session holds */ }
          return { pub: slots.active.pub };
        });
      });
    } catch (e) { return Promise.reject(e); }
  }

  /* handleSignRequest: the full REQ_SIGN flow. Params: origin string,
   *   payload {unsigned, accountId, label?, remember?}, opts {walletSelf}.
   *   Resolves {intentId} once the approval is OPEN (the requester waits on
   *   the intent via its own path); the final proof is delivered through
   *   the intent journal + the original message reply on settle. Rate
   *   limits, shape gates, chain binding, and one-at-a-time run first —
   *   rejections here never open a tab. */
  function handleSignRequest(origin, payload, opts) {
    var walletSelf = !!(opts && opts.walletSelf);
    var nowMs = Date.now();
    var activeChainId = null;
    var allowlist = {};
    var budgets = {};
    if (!payload || typeof payload !== "object") return Promise.reject(new Error("bad payload"));
    if (typeof Bridge === "undefined" || !Bridge || typeof Bridge.isValidUnsignedTx !== "function") {
      return Promise.reject(new Error("gate misconfigured"));
    }
    if (!Bridge.isValidUnsignedTx(payload.unsigned)) {
      return Promise.reject(new Error("unsigned tx has bad shape"));
    }
    var accountId = payload.accountId;
    if (typeof accountId !== "string" || !accountId) {
      return Promise.reject(new Error("missing account"));
    }
    return ensureChain().then(function (chainId) {
      activeChainId = chainId;
      if (!walletSelf) {
        if (!Bridge.isHttpsOrigin(origin)) throw new Error("origin not https");
        if (!Bridge.checkChainId(payload.chainId, activeChainId)) throw new Error("chain_id mismatch");
      }
      return getAllowlist();
    }).then(function (a) {
      allowlist = a;
      if (!walletSelf) {
        var chk = Bridge.validateRequest(
          { origin: origin, chainId: payload.chainId, accountId: accountId },
          { activeChainId: activeChainId, allowlist: allowlist });
        if (!chk.ok) {
          /* Not-yet-approved is a distinct outcome: the approval page
           * offers the remember-checkbox, so the request proceeds to
           * prompt rather than rejecting outright. Other reasons deny. */
          if (chk.reason !== "account not approved for origin") throw new Error(chk.reason);
        }
      }
      return SessionVault.sessionGet([SessionVault.K_RATE]).then(function (items) {
        budgets = (items && items[SessionVault.K_RATE]) || {};
        var rl = Bridge.checkRateLimit(budgets, origin || "wallet-self", nowMs);
        var o = {};
        o[SessionVault.K_RATE] = rl.state;
        return SessionVault.sessionSet(o).catch(function () {}).then(function () {
          if (!rl.allow) throw new Error("rate limited: too many requests");
          return SessionVault.sessionGet([K_PENDING]);
        });
      });
    }).then(function (items) {
      var pending = items ? items[K_PENDING] : null;
      if (pending) throw new Error("approval busy: another request is pending");
      return enrichUnsigned(payload.unsigned);
    }).then(function (enriched) {
      var id = "in-" + String(nowMs) + "-" + Math.floor(Math.random() * 1e9).toString(36);
      var intent = {
        id: id, origin: walletSelf ? Bridge.WALLET_SELF : origin,
        walletSelf: walletSelf, accountId: accountId,
        label: (payload.label && String(payload.label)) || "",
        chainId: activeChainId, unsigned: payload.unsigned,
        enriched: enriched, status: "pending", createdAt: nowMs,
        remember: walletSelf ? false : (payload.remember !== false)
      };
      return getJournal().then(function (j) {
        j[id] = intent;
        return setJournal(j).then(function () {
          var o = {};
          o[K_PENDING] = id;
          return SessionVault.sessionSet(o).catch(function () {});
        }).then(function () {
          armDeadline(id);
          return openApproval(id).then(function () { return { intentId: id }; });
        });
      });
    });
  }

  /* approveIntent: approval-page decision handler. Params: intentId,
   *   password (string, may be "" when the session is already unlocked),
   *   remember (bool, ignored for wallet-self). Flow: load intent (must be
   *   pending) -> ensure session keys (unlock when needed) -> re-match ops
   *   to the receipt (unsigned bytes unchanged since prompt) -> sign each
   *   op set with the ACTIVE wif -> broadcast (SW ack) -> optional allowlist
   *   write -> settle with proof. Rejects verbatim (approval page renders). */
  function approveIntent(intentId, password, remember) {
    var intent = null, keys = null;
    return getJournal().then(function (j) {
      intent = j[intentId] || null;
      if (!intent || intent.status !== "pending") throw new Error("intent not pending");
      return readSessionKeys();
    }).then(function (k) {
      keys = k;
      if (!keys) {
        return unlockSession(password).then(function () { return readSessionKeys(); })
          .then(function (k2) {
            keys = k2;
            if (!keys) throw new Error("unlock failed");
          });
      }
    }).then(function () {
      /* Receipt match: the unsigned payload must be byte-identical to what
       * the approval page rendered (journal is the receipt — the page
       * rendered from it, so any mutation between prompt and approve can
       * only come from a compromised journal write, which still fails
       * closed here by re-validating shape). */
      if (!Bridge.isValidUnsignedTx(intent.unsigned)) throw new Error("receipt mismatch");
      if (typeof Tx === "undefined" || !Tx || typeof Tx.sign !== "function") {
        throw new Error("signer missing in SW");
      }
      var txObj = JSON.parse(JSON.stringify(intent.unsigned));
      return Tx.sign(txObj, keys.active.wif);
    }).then(function (signed) {
      return swBroadcast(signed).then(function (ack) {
        var proof = { via: ack.via, headBefore: ack.headBefore, intentId: intent.id };
        var done = function () {
          return settleIntent(intent.id, { status: "approved", proof: proof }).then(function () {
            return proof;
          });
        };
        if (!intent.walletSelf && remember !== false && intent.remember) {
          return getAllowlist().then(function (a) {
            var entry = a[intent.origin] || { allowedAccountIds: [] };
            if (!Array.isArray(entry.allowedAccountIds)) entry.allowedAccountIds = [];
            if (entry.allowedAccountIds.indexOf(intent.accountId) === -1) {
              entry.allowedAccountIds.push(intent.accountId);
            }
            entry.lastApproved = Date.now();
            a[intent.origin] = entry;
            return setAllowlist(a).catch(function () {});
          }).then(done);
        }
        return done();
      });
    }).catch(function (e) {
      return settleIntent(intentId, { status: "denied", error: (e && e.message) || String(e) })
        .then(function () { throw e; });
    });
  }

  /* denyIntent: approval-page denial (or tab-close / deadline). Settles the
   * journal; never throws outward. */
  function denyIntent(intentId, reason) {
    try {
      return settleIntent(intentId, { status: "denied", error: reason || "denied" })
        .catch(function () { return true; });
    } catch (e) { return Promise.resolve(true); }
  }

  /* getIntent: approval-page render fetch (must be pending; settled intents
   * return their outcome once for display, then stay settled). */
  function getIntent(intentId) {
    return getJournal().then(function (j) {
      var it = j[intentId] || null;
      if (!it) throw new Error("unknown intent");
      return {
        id: it.id, origin: it.origin, walletSelf: !!it.walletSelf,
        accountId: it.accountId, label: it.label, chainId: it.chainId,
        enriched: it.enriched, status: it.status,
        createdAt: it.createdAt, error: it.error || null, proof: it.proof || null
      };
    });
  }

  /* onMessage: SW router. Returns true when a reply will be sent async
   * (caller must return true to keep the channel open). */
  function onMessage(msg, sender, sendReply) {
    try {
      if (!msg || typeof msg !== "object" || typeof msg.type !== "string") return false;
      var type = msg.type, id = msg.id;
      function reply(ok, payload, error) {
        try {
          if (typeof sendReply === "function") {
            sendReply({ id: id, ok: !!ok,
              payload: (payload === undefined ? null : payload),
              error: (error === undefined ? null : String(error)) });
          }
        } catch (e) { /* channel gone */ }
      }
      /* Extension-page direct calls (approval page, wallet page). */
      if (isExtensionPage(sender)) {
        if (type === "vb-intent-get") {
          getIntent(msg.intentId).then(
            function (it) { reply(true, it); },
            function (e) { reply(false, null, (e && e.message) || String(e)); });
          return true;
        }
        if (type === "vb-approve") {
          approveIntent(msg.intentId, msg.password || "", msg.remember)
            .then(function (proof) { reply(true, proof); },
              function (e) { reply(false, null, (e && e.message) || String(e)); });
          return true;
        }
        if (type === "vb-deny") {
          denyIntent(msg.intentId, "denied in approval page").then(function () {
            reply(true, { denied: true });
          });
          return true;
        }
        if (type === "vb-wallet-sign") {
          var p = msg.payload || {};
          handleSignRequest(Bridge.WALLET_SELF,
            { unsigned: p.unsigned, accountId: p.accountId, label: p.label },
            { walletSelf: true }).then(function (r) {
              /* Wallet-self proof delivery: the wallet page learns the
               * outcome by polling the intent (same journal the approval
               * page reads) — reply acknowledges receipt of the request. */
              reply(true, r);
            }, function (e) { reply(false, null, (e && e.message) || String(e)); });
          return true;
        }
        if (type === "vb-session-state") {
          readSessionKeys().then(function (k) {
            reply(true, { unlocked: !!k });
          });
          return true;
        }
        return false;
      }
      /* dApp relay calls (content script attached the origin). */
      var origin = senderOrigin(msg, sender);
      if (type === Bridge.REQ_CHAIN_ID) {
        ensureChain().then(function (chainId) { reply(true, { chainId: chainId }); },
          function (e) { reply(false, null, (e && e.message) || String(e)); });
        return true;
      }
      if (type === Bridge.REQ_ACCOUNT) {
        getAllowlist().then(function (a) {
          var entry = a[origin] || null;
          var ids = (entry && Array.isArray(entry.allowedAccountIds)) ? entry.allowedAccountIds : [];
          reply(true, { origin: origin, accountIds: ids });
        });
        return true;
      }
      if (type === Bridge.REQ_SIGN) {
        var p2 = msg.payload || {};
        handleSignRequest(origin,
          { unsigned: p2.unsigned, accountId: p2.accountId,
            label: p2.label, chainId: p2.chainId, remember: p2.remember },
          { walletSelf: false }).then(function (r) { reply(true, r); },
          function (e) { reply(false, null, (e && e.message) || String(e)); });
        return true;
      }
      return false;
    } catch (e) { return false; }
  }

  /* onAlarm: approval deadlines (deny) — the vb-lock alarm keeps its
   * existing sw.js handler; gate arms only vb-approve-* alarms. */
  function onAlarm(alarm) {
    try {
      if (!alarm || typeof alarm.name !== "string") return;
      if (alarm.name.indexOf(ALARM_PREFIX) !== 0) return;
      var id = alarm.name.slice(ALARM_PREFIX.length);
      denyIntent(id, "approval timed out after 60s");
    } catch (e) { /* deadline best-effort; requester ceiling covers */ }
  }

  /* onTabRemoved: approval tab closed without deciding denies the intent
   * (closing is not consent — the central anti-spoof rule). Needs the
   * intent->tab map; approval tabs are tracked at open. Best-effort. */
  var _tabIntents = {};
  function noteApprovalTab(intentId, tabId) {
    try { if (tabId !== null && tabId !== undefined) _tabIntents[tabId] = intentId; } catch (e) {}
  }
  function onTabRemoved(tabId) {
    try {
      var id = _tabIntents[tabId];
      if (id) {
        try { delete _tabIntents[tabId]; } catch (e) {}
        getJournal().then(function (j) {
          if (j[id] && j[id].status === "pending") denyIntent(id, "approval tab closed");
        }).catch(function () {});
      }
    } catch (e) { /* teardown best-effort */ }
  }

  return {
    opName: opName,
    senderOrigin: senderOrigin,
    isExtensionPage: isExtensionPage,
    readSettings: readSettings,
    ensureChain: ensureChain,
    collectAssetIds: collectAssetIds,
    humanizeFields: humanizeFields,
    enrichUnsigned: enrichUnsigned,
    swBroadcast: swBroadcast,
    getJournal: getJournal,
    getAllowlist: getAllowlist,
    openApproval: openApproval,
    approveIntent: approveIntent,
    denyIntent: denyIntent,
    getIntent: getIntent,
    unlockSession: unlockSession,
    readSessionKeys: readSessionKeys,
    wipeSession: wipeSession,
    denyPending: denyPending,
    handleSignRequest: handleSignRequest,
    onMessage: onMessage,
    onAlarm: onAlarm,
    noteApprovalTab: noteApprovalTab,
    onTabRemoved: onTabRemoved,
    ALARM_PREFIX: ALARM_PREFIX
  };
})();

if (typeof module !== "undefined") { module.exports = Gate; }
