#!/usr/bin/env python3
"""Regenerate vanilla/js/data/brainkey-dict.js from the reference dictionary.
Stdlib only. Run from /workspace."""
import json

with open("reference/bitshares-ui/app/lib/common/dictionary_en.json") as fh:
    words = json.load(fh)["en"].split(",")
print("words:", len(words))
assert len(words) == 49744, "expected 49744 dictionary words"
with open("vanilla/js/data/brainkey-dict.js", "w") as fh:
    fh.write('/* 49,744-word brainkey dictionary. Generated by\n'
             '   tooling/extract_brainkey_dict.py — do not edit. */\n'
             'var BRAINKEY_DICT = "')
    fh.write(",".join(words))
    fh.write('";\n')
    fh.write('if (typeof module !== "undefined") { module.exports = BRAINKEY_DICT; }\n')
print("wrote vanilla/js/data/brainkey-dict.js")
