#!/usr/bin/env python3
"""gen_tier2_opnames.py — emit the Tier 2 approval-page op-name table.

Reads the machine spec oracle (reference/open-graphene, 78 ops, tags 0-77)
and prints a JS object literal mapping op id -> human label, using the same
convention as vanilla/js/views/account-ui.js OP_LABELS ("Limit order
create", "Call order update", ...): strip the trailing _operation suffix,
replace underscores with spaces, capitalize the first letter only.

Reference-only input, never a dependency: the printed table is pasted into
extension-wrapper/background/gate.js with a provenance comment. Rerun to
verify the embedded copy (diff stdout against the table in gate.js).

Usage: python3 tooling/gen_tier2_opnames.py
"""
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SPEC = os.path.join(
    HERE, "..", "reference", "open-graphene", "open-graphene-packages",
    "rust", "graphene-chain-bitshares", "graphene-chain-bitshares-spec",
    "dist", "bitshares.open-graphene.json")


def humanize(name):
    base = name[:-len("_operation")] if name.endswith("_operation") else name
    label = base.replace("_", " ")
    return label[:1].upper() + label[1:] if label else name


def main():
    try:
        with io.open(SPEC, encoding="utf-8") as f:
            spec = json.load(f)
    except (OSError, ValueError) as e:
        print("spec unreadable: %s" % e, file=sys.stderr)
        return 1
    ops = spec.get("operations")
    if not isinstance(ops, list) or len(ops) != 78:
        print("expected 78 operations, got %s" % (
            len(ops) if isinstance(ops, list) else type(ops)), file=sys.stderr)
        return 1
    print("/* Generated by tooling/gen_tier2_opnames.py from the open-graphene")
    print(" * machine spec (78 ops, tags 0-77). Human-label convention matches")
    print(" * vanilla/js/views/account-ui.js OP_LABELS. */")
    print("var OP_NAMES = {")
    for i, op in enumerate(ops):
        name = op.get("name") if isinstance(op, dict) else None
        if not name:
            print("op %d has no name" % i, file=sys.stderr)
            return 1
        print("  %d: %s," % (i, json.dumps(humanize(name))))
    print("};")
    return 0


if __name__ == "__main__":
    sys.exit(main())
