"""Rewrite the build-dialog exchange count out of the locale dicts.

Why: the count lives in a generated asset (vanilla/assets/build-dialog.js,
regenerated by tooling/collate_vanilla_prompts.py) that grew 413 -> 739 when
22 missed sessions were recovered. Three About-page strings hardcoded "413"
as a literal, in all 12 dicts, so every one went stale at once and the
English default in about-ui.js disagreed with the dict. The count is now
interpolated at render time (about.dlg_bad_link takes %(total)s), so the
dicts must carry the placeholder too.

This script reads the live count from the asset, rewrites the affected keys
in every locale, and prints what changed. Idempotent.

Usage: python3 tooling/sync_build_dialog_count_i18n.py
"""

import json
import re
import sys

ASSET = "/workspace/vanilla/assets/build-dialog.js"
LOCALES_DIR = "/workspace/vanilla/locales"
LOCALES = ["en", "de", "es", "fr", "hi", "it", "ja", "ko", "pt", "ru", "tr", "zh"]

# Any "1-413" / "1–413" / "413 exchanges" phrasing collapses to the
# placeholder; the surrounding translator's words are preserved verbatim.
BAD_LINK_RE = re.compile(r"(1[\s\u2013\u2014-]*)\s*413")
EXCHANGES_RE = re.compile(r"\b413\s+(exchanges|exchanges\b|exchange)")


def asset_total() -> int:
    with open(ASSET, encoding="utf-8") as f:
        head = f.read(400)
    m = re.search(r"Build-dialog archive: (\d+)", head)
    if not m:
        sys.exit("could not read exchange count from " + ASSET)
    return int(m.group(1))


def rewrite(dic: dict, total: int) -> list[str]:
    """Returns human-readable notes for each key changed."""
    notes = []
    about = dic.get("about", {})

    bad = about.get("dlg_bad_link")
    if isinstance(bad, str) and "413" in bad:
        # Preserve each locale's own range dash (– vs - vs ：) — only the
        # number becomes a placeholder.
        about["dlg_bad_link"] = BAD_LINK_RE.sub(lambda m: m.group(1) + "%(total)s", bad)
        if "total" not in about["dlg_bad_link"]:
            about["dlg_bad_link"] = bad.replace("413", "%(total)s")
        notes.append("about.dlg_bad_link")

    body = about.get("making_body")
    if isinstance(body, str) and "413" in body:
        # "413 exchanges across 14 sessions" -> "%(total)s exchanges across
        # 37 sessions" is not derivable per-locale, so drop the count clause
        # rather than invent a translated one: the live count is already
        # shown in the "Full build dialog (N)" heading right below.
        body = re.sub(r"\s*413\s+exchanges\s+across\s+14\s+sessions\.", "", body)
        body = EXCHANGES_RE.sub("%(total)s exchanges", body)
        about["making_body"] = body
        notes.append("about.making_body")

    for key, val in list(about.items()):
        if isinstance(val, str) and "413 exchanges" in val and key != "making_body":
            about[key] = val.replace("413 exchanges", "%(total)s exchanges")
            notes.append("about." + key)

    return notes


def strip_help_counts(dic: dict) -> list[str]:
    """Drop the count clause from the About help article.

    help-ui.js renders help.topic_<key>_text/_body through the same t() with
    NO vars argument, so a %(total)s placeholder there would print literally.
    The count is therefore removed from the prose instead — the About page's
    "Full build dialog (N)" heading is the one place the live number shows.
    """
    notes = []
    help = dic.get("help", {})

    # The count appears in three shapes across the 12 dicts:
    #   teaser, end of _text :  "— 413 exchanges across 14 sessions."
    #   own line in _body   :  "413 exchanges across 14 sessions. Read it…"
    #   mid-sentence        :  "browse all 413 exchanges, filter by…"
    # Strip the clause; keep the translator's own nouns and punctuation.
    OWN_LINE = r"[ \t]*\n?413\s+\S+\s+(?:across|en)\s+14\s+(?:sessions|sesiones)\."
    TEASER = r"([\u2014\u2013-])\s*413\s+[^.\n]*\.\s*$"
    # "all 413 exchanges" / "los 413 intercambios" — keep the determiner and
    # noun, drop the number.
    MID = r"\b(all|los|las|die)\s+413\s+(\S+)"

    for key in ("topic_about-making_text", "topic_about-making_body"):
        val = help.get(key)
        if not isinstance(val, str) or "413" not in val:
            continue
        cut = re.sub(OWN_LINE, "", val)
        cut = re.sub(TEASER, lambda m: m.group(1), cut)
        cut = re.sub(MID, lambda m: m.group(1) + " " + m.group(2), cut)
        if "413" in cut:  # a shape we do not recognize — never guess
            print("  WARNING: %s still holds 413; inspect by hand" % key)
            continue
        cut = re.sub(r"[ \t]{2,}", " ", cut).rstrip()
        help[key] = cut
        notes.append("help." + key)
    return notes


def main() -> None:
    total = asset_total()
    print(f"live exchange count in asset: {total}")
    for loc in LOCALES:
        path = f"{LOCALES_DIR}/{loc}.json"
        with open(path, encoding="utf-8") as f:
            dic = json.load(f)
        notes = rewrite(dic, total) + strip_help_counts(dic)
        if not notes:
            print(f"  {loc}: already current")
            continue
        with open(path, "w", encoding="utf-8") as f:
            json.dump(dic, f, ensure_ascii=False, indent=2)
            f.write("\n")
        print(f"  {loc}: rewrote {', '.join(sorted(set(notes)))}")


if __name__ == "__main__":
    main()
